import sys
import os
import json
import time

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from agents.chief_editor import ChiefEditorAgent
from shared.feishu_client import FeishuClient
from shared import config

def run():
    print("\n" + "=" * 50)
    print("🤖 启动 Agentic Workflow (Step 2: Article Gen)")
    print("=" * 50 + "\n")
    
    # Init
    editor = ChiefEditorAgent()
    client = FeishuClient()
    
    # Load Topics (Generated by Step 1)
    # 实际生产中应该从飞书读 Pending 状态的记录，或者从 json 文件读
    # 这里演示从 generated_seo_data.json 读，并模拟写入飞书
    
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    INPUT_FILE = os.path.join(BASE_DIR, 'generated_seo_data.json')
    
    if not os.path.exists(INPUT_FILE):
        print("❌ 未找到选题文件，请先运行 Step 1")
        return
        
    with open(INPUT_FILE, 'r', encoding='utf-8') as f:
        topics = json.load(f)
        
    # 过滤 Pending
    pending_topics = [t for t in topics if t.get('Status') == 'Pending']
    print(f"📋 发现 {len(pending_topics)} 个待写选题")
    
    for item in pending_topics[:5]: # 演示只跑5个
        article = editor.write_article(item['Topic'], item['大项分类'])
        
        if article:
            # Save to Feishu (System Action)
            # 同样，Agent 只负责产出，IO由系统层负责
            record = {
                "Topic": item['Topic'],
                "Title": article.get('title'),
                "HTML_Content": article.get('html_content'),
                "Category": item['大项分类'],
                "Status": "Generated", # 待发布
                "Keywords": article.get('keywords'),
                "Summary": article.get('summary'),
                "Description": article.get('description'),
                "Tags": article.get('tags'),
                "One_Line_Summary": article.get('one_line_summary'),
                "Schema_FAQ": json.dumps(article.get('schema_faq', []), ensure_ascii=False)
            }
            res_id = client.create_record(record)
            if res_id:
                print(f"   💾 已保存至飞书 (ID: {res_id})")
                item['Status'] = 'Done' # Update local status
        
        time.sleep(2)
        
    # Update JSON
    with open(INPUT_FILE, 'w', encoding='utf-8') as f:
        json.dump(topics, f, ensure_ascii=False, indent=2)

if __name__ == "__main__":
    run()
